// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVFU4PBaVOxA9e_D5E41WSWBF-C9s3jvE',
    appId: '1:1067475332172:web:78c2647b2e11796a45d8e9',
    messagingSenderId: '1067475332172',
    projectId: 'cook1ng',
    authDomain: 'cook1ng.firebaseapp.com',
    storageBucket: 'cook1ng.appspot.com',
    measurementId: 'G-8RWCVL4FMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChkS20TNkbT6XzVEa3UqGWBj8mMR4JeHI',
    appId: '1:1067475332172:android:75ed15832eb17a5845d8e9',
    messagingSenderId: '1067475332172',
    projectId: 'cook1ng',
    storageBucket: 'cook1ng.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDScIIaxrJQaVuSEBQkuscglah5uhXyY',
    appId: '1:1067475332172:ios:73ee21ef746c62f145d8e9',
    messagingSenderId: '1067475332172',
    projectId: 'cook1ng',
    storageBucket: 'cook1ng.appspot.com',
    iosClientId: '1067475332172-83e6n8t8i2na5tqnilsln09b3pllli9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.alDente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvDScIIaxrJQaVuSEBQkuscglah5uhXyY',
    appId: '1:1067475332172:ios:73ee21ef746c62f145d8e9',
    messagingSenderId: '1067475332172',
    projectId: 'cook1ng',
    storageBucket: 'cook1ng.appspot.com',
    iosClientId: '1067475332172-83e6n8t8i2na5tqnilsln09b3pllli9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.alDente',
  );
}
